#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp /tmp/resource-check.XXXXXX)

cat > "$payload" <&0

name="$(jq -r '.source.name' < "$payload")"
region="$(jq -r '.source.region' < "$payload")"

if [ -z "$region" ]; then
  echo "no region specified"
  exit 1
fi
if [ -z "$name" ]; then
  echo "no name specified"
  exit 1
fi

export AWS_DEFAULT_REGION="$region"

# get some metadata
versions=$(aws ec2 describe-images --filter Name=name,Values="${name}" | jq -r '.Images|map({ImageId,Region})|.[0]["Region"] = "'"$region"'"')

jq -n "${versions}" >&3
