#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

export AWS_DEFAULT_REGION=$(cat $payload|jq -r '.params.region // .source.region')

ami_id="$(cat $payload|jq -r '.version.ImageId')"

# wait for image to be available
aws ec2 wait image-available $ami_id

# get some metadata
metadata=$(aws ec2 describe-images --image-ids $ami_id | jq -r '.Images[0]|{Name,CreationDate,OwnerId}'

jq -n "{
  version: ${response},
  metadata: ${metadata}
}" >&3
